/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkoutRouteImport } from './routes/_app.workout'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoutinesRouteImport } from './routes/_app.routines'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppHistoryIdRouteImport } from './routes/_app.history.$id'
import { Route as AppExerciseIdRouteImport } from './routes/_app.exercise.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutRoute = AppWorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesRoute = AppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryIdRoute = AppHistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppHistoryRoute,
} as any)
const AppExerciseIdRoute = AppExerciseIdRouteImport.update({
  id: '/exercise/$id',
  path: '/exercise/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof AppHistoryRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/routines': typeof AppRoutinesRoute
  '/settings': typeof AppSettingsRoute
  '/workout': typeof AppWorkoutRoute
  '/history/$id': typeof AppHistoryIdRoute
  '/exercise/$id': typeof AppExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof AppHistoryRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/routines': typeof AppRoutinesRoute
  '/settings': typeof AppSettingsRoute
  '/workout': typeof AppWorkoutRoute
  '/history/$id': typeof AppHistoryIdRoute
  '/exercise/$id': typeof AppExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/history': typeof AppHistoryRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/routines': typeof AppRoutinesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/workout': typeof AppWorkoutRoute
  '/_app/history/$id': typeof AppHistoryIdRoute
  '/_app/exercise/$id': typeof AppExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/profile'
    | '/routines'
    | '/settings'
    | '/workout'
    | '/history/$id'
    | '/exercise/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/profile'
    | '/routines'
    | '/settings'
    | '/workout'
    | '/history/$id'
    | '/exercise/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/history'
    | '/_app/profile'
    | '/_app/routines'
    | '/_app/settings'
    | '/_app/workout'
    | '/_app/history/$id'
    | '/_app/exercise/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workout': {
      id: '/_app/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof AppWorkoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines': {
      id: '/_app/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AppRoutinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history/$id': {
      id: '/_app/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof AppHistoryIdRouteImport
      parentRoute: typeof AppHistoryRoute
    }
    '/_app/exercise/$id': {
      id: '/_app/exercise/$id'
      path: '/exercise/$id'
      fullPath: '/exercise/$id'
      preLoaderRoute: typeof AppExerciseIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppHistoryRouteChildren {
  AppHistoryIdRoute: typeof AppHistoryIdRoute
}

const AppHistoryRouteChildren: AppHistoryRouteChildren = {
  AppHistoryIdRoute: AppHistoryIdRoute,
}

const AppHistoryRouteWithChildren = AppHistoryRoute._addFileChildren(
  AppHistoryRouteChildren,
)

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppRoutinesRoute: typeof AppRoutinesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorkoutRoute: typeof AppWorkoutRoute
  AppExerciseIdRoute: typeof AppExerciseIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppRoutinesRoute: AppRoutinesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWorkoutRoute: AppWorkoutRoute,
  AppExerciseIdRoute: AppExerciseIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
